apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-nisw
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qprx-tenant/rhtap-demo-app/hacbs-test-project-nisw@sha256:4d830e2c0fd7746316e6954f1ae943246400bc4158dcb032c4b0be8b62ffb204
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
