apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-nisw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-nisw
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-nisw
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-nisw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-nisw
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qprx-tenant/rhtap-demo-app/hacbs-test-project-nisw@sha256:4d830e2c0fd7746316e6954f1ae943246400bc4158dcb032c4b0be8b62ffb204
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
